import type { TemplateDef } from './types'

// MotionGrid marketing/lead email templates. These are separate from the
// Autofield workshop templates: they use MotionGrid branding and are sent via
// lib/marketing-email.ts (env-based sender, no workshop lookup).
export const MARKETING_TEMPLATES: Record<string, TemplateDef> = {
  contact_form_submission: {
    subject: 'New contact form submission from {{name}}',
    text: [
      'New contact form submission received on the MotionGrid website.',
      '',
      'Name: {{name}}',
      'Company: {{company}}',
      'Email: {{email}}',
      'Phone: {{phone}}',
      '',
      'Message:',
      '{{message}}',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>{{businessName}}</h2>',
      '<p>A new contact form submission was received:</p>',
      '<table style="width:100%;border-collapse:collapse;margin:16px 0;">',
      '<tr><td style="padding:6px 0;"><strong>Name</strong></td><td>{{name}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Company</strong></td><td>{{company}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Email</strong></td><td>{{email}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Phone</strong></td><td>{{phone}}</td></tr>',
      '</table>',
      '<div style="background:#f9fafb;border-radius:8px;padding:16px;margin:16px 0;">',
      '<p style="margin:0;"><strong>Message</strong></p>',
      '<p style="margin:8px 0 0;">{{message}}</p>',
      '</div>',
      '</div>',
    ].join(''),
  },

  demo_request_confirmation: {
    subject: 'Thanks for your interest, {{name}}',
    text: [
      'Hi {{name}},',
      '',
      'Thanks for reaching out to {{businessName}}.',
      '',
      'We have received your demo request and will be in touch shortly to schedule a session that fits your schedule.',
      '',
      'In the meantime, feel free to explore our live sandbox and micro-tools on the site.',
      '',
      'Talk soon,',
      'The {{businessName}} team',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>{{businessName}}</h2>',
      '<p>Hi {{name}},</p>',
      '<p>Thanks for reaching out. We have received your demo request and will be in touch shortly to schedule a session that fits your schedule.</p>',
      '<p>In the meantime, feel free to explore our live sandbox and micro-tools on the site.</p>',
      '<p style="font-size:12px;color:#9ca3af;margin-top:24px;">&mdash; The {{businessName}} team</p>',
      '</div>',
    ].join(''),
  },

  // ── Slot booking flow (Phase 3.3) ──────────────────────────────────

  booking_confirmation: {
    subject: 'Your {{businessName}} demo is booked — {{slot}}',
    text: [
      'Hi {{name}},',
      '',
      'Your {{duration}}-minute demo call with {{businessName}} is booked:',
      '',
      'When: {{slot}} (South Africa, SAST)',
      'Duration: {{duration}} minutes',
      '',
      'A calendar invite is attached — accept it and the slot lands in your calendar with a reminder.',
      '',
      'Need a different time? Just reply to this email and we will reschedule.',
      '',
      'Talk soon,',
      'The {{businessName}} team',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>{{businessName}}</h2>',
      '<p>Hi {{name}},</p>',
      '<p>Your <strong>{{duration}}-minute demo call</strong> is booked:</p>',
      '<table style="width:100%;border-collapse:collapse;margin:16px 0;">',
      '<tr><td style="padding:6px 0;"><strong>When</strong></td><td>{{slot}} (SAST)</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Duration</strong></td><td>{{duration}} minutes</td></tr>',
      '</table>',
      '<p>A calendar invite is attached — accept it and the slot lands in your calendar with a reminder.</p>',
      '<p style="font-size:12px;color:#9ca3af;">Need a different time? Just reply and we will reschedule.</p>',
      '<p style="font-size:12px;color:#9ca3af;margin-top:24px;">&mdash; The {{businessName}} team</p>',
      '</div>',
    ].join(''),
  },

  booking_notification_admin: {
    subject: 'New demo booking — {{name}} on {{slot}}',
    text: [
      'A demo slot was booked on the {{businessName}} website.',
      '',
      'When: {{slot}} (SAST)',
      'Duration: {{duration}} minutes',
      '',
      'Name: {{name}}',
      'Company: {{company}}',
      'Email: {{email}}',
      'Phone: {{phone}}',
      '',
      'Message:',
      '{{message}}',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>New demo booking</h2>',
      '<p><strong>{{slot}}</strong> (SAST) &middot; {{duration}} minutes</p>',
      '<table style="width:100%;border-collapse:collapse;margin:16px 0;">',
      '<tr><td style="padding:6px 0;"><strong>Name</strong></td><td>{{name}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Company</strong></td><td>{{company}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Email</strong></td><td>{{email}}</td></tr>',
      '<tr><td style="padding:6px 0;"><strong>Phone</strong></td><td>{{phone}}</td></tr>',
      '</table>',
      '<div style="background:#f9fafb;border-radius:8px;padding:16px;margin:16px 0;">',
      '<p style="margin:0;"><strong>Message</strong></p>',
      '<p style="margin:8px 0 0;">{{message}}</p>',
      '</div>',
      '</div>',
    ].join(''),
  },

  // ── Welcome email sequence (Phase 5) ──────────────────────────────
  // Step 1 is sent immediately when a lead is enrolled; steps 2 and 3 are
  // sent by the sequence runner (lib/email-sequences.ts) via the cron route.

  welcome_email_1: {
    subject: 'Welcome aboard, {{name}} — here is what happens next',
    text: [
      'Hi {{name}},',
      '',
      'Welcome to {{businessName}}. Here is what to expect over the next few days:',
      '',
      '1. We read every enquiry ourselves — one of the founders will personally come back to you.',
      '2. If you left a message, we will come prepared with questions, not a sales script.',
      '3. Want to move faster? Book a 15-minute slot directly on our contact page.',
      '',
      'Talk soon,',
      'The {{businessName}} team',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>{{businessName}}</h2>',
      '<p>Hi {{name}},</p>',
      '<p>Welcome aboard. Here is what to expect over the next few days:</p>',
      '<ol style="padding-left:20px;line-height:1.8;">',
      '<li>We read every enquiry ourselves — one of the founders will personally come back to you.</li>',
      '<li>If you left a message, we will come prepared with questions, not a sales script.</li>',
      '<li>Want to move faster? Book a 15-minute slot directly on our contact page.</li>',
      '</ol>',
      '<p style="font-size:12px;color:#9ca3af;margin-top:24px;">&mdash; The {{businessName}} team</p>',
      '</div>',
    ].join(''),
  },

  welcome_email_2: {
    subject: '{{name}}, see the system live before we talk',
    text: [
      'Hi {{name}},',
      '',
      'While your enquiry sits with us, two quick things worth two minutes:',
      '',
      '- The sandbox on our site runs live code from our stack — no mockups.',
      '- The tools page lists the micro-tools we ship fastest (VIN decoder, site auditor and friends).',
      '',
      'Anything you see there that maps to your problem, mention it when we talk — it speeds everything up.',
      '',
      'The {{businessName}} team',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>See it live first</h2>',
      '<p>Hi {{name}},</p>',
      '<p>While your enquiry sits with us, two quick things worth two minutes:</p>',
      '<ul style="padding-left:20px;line-height:1.8;">',
      '<li>The <strong>sandbox</strong> on our site runs live code from our stack — no mockups.</li>',
      '<li>The <strong>tools page</strong> lists the micro-tools we ship fastest.</li>',
      '</ul>',
      '<p>Anything there that maps to your problem, mention it when we talk — it speeds everything up.</p>',
      '<p style="font-size:12px;color:#9ca3af;margin-top:24px;">&mdash; The {{businessName}} team</p>',
      '</div>',
    ].join(''),
  },

  welcome_email_3: {
    subject: 'Still want that demo, {{name}}?',
    text: [
      'Hi {{name}},',
      '',
      'Your enquiry is still open on our side. If the timing was wrong, no problem — the 15-minute slots on our contact page are always live, and picking one is the fastest way to reach us.',
      '',
      'If you have already moved on, ignore this email and we will close the loop quietly.',
      '',
      'The {{businessName}} team',
    ].join('\n'),
    html: [
      '<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1f2937;">',
      '<h2>Still want that demo?</h2>',
      '<p>Hi {{name}},</p>',
      '<p>Your enquiry is still open on our side. If the timing was wrong, no problem — the 15-minute slots on our <a href="{{siteUrl}}/contact">contact page</a> are always live, and picking one is the fastest way to reach us.</p>',
      '<p>If you have already moved on, ignore this email and we will close the loop quietly.</p>',
      '<p style="font-size:12px;color:#9ca3af;margin-top:24px;">&mdash; The {{businessName}} team</p>',
      '</div>',
    ].join(''),
  },
}
